I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 56, in script
    if not p:
  File "game/script.rpy", line 56, in <module>
    if not p:
NameError: name 'p' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 56, in script
    if not p:
  File "D:\renpy\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "D:\renpy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 56, in <module>
    if not p:
NameError: name 'p' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Haustorium 1.0
Sun Feb  5 12:35:57 2023
